---
title: "explorationsection_graphs"
author: "Maggie O'Shea"
date: "4/17/2022"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyverse)

library(lubridate)
library(trend)

Databyyear <- read.csv("./Data/alldatabyyear.csv")

inflationadjusted <- read.csv("./Data/inflationadjusted.csv")

inflationadjusted[is.na(inflationadjusted)] <- 0
```

```{r summarize totals for graphs}

totals <- Databyyear%>%
  summarise('Ex-Situ' = sum(Buyouts_propertiesamountpaid),
            'In-Situ' = sum(insituproperties_amountpaid),
            'All Adaptation' = sum(Floodproperties_amountpaid), 
            `Ex-Situ Properties` = sum(Buyouts_propertiesperyear), 
            'In-Situ Properties' = sum(insitupropertiesperyear), 
            'All Properties' = sum(Floodpropertiesperyear))

totals_inflation <- inflationadjusted%>%
    summarise(`Ex-Situ` = sum(Buyouts_propertiesamountpaid),
            `In-Situ` = sum(insituproperties_amountpaid),
            `All Adaptation` = sum(Floodproperties_amountpaid),
            `Ex-Situ - Inflation` = sum(InflationAdjusted_BUYOUTAmountpaid),
            `In-Situ - Inflation` = sum(InflationAdjusted_INSITUAmountpaid),
            `All Adaptation - Inflation` = sum(InflationAdjusted_AllAmountpaid))
  
```


```{r}
totals_pivot <- pivot_longer(totals, `Ex-Situ`:`All Properties`, names_to = "Category", values_to = "Total")

totals_properties <- totals%>%
  select(`Ex-Situ Properties`, 
            `In-Situ Properties`, 
            `All Properties`)

totalprops_pivot <- pivot_longer(totals_properties, `Ex-Situ Properties`:`All Properties`, names_to = "Category", values_to = "Total")

write.csv(totalprops_pivot, './Data/totalproperties_explorationgraph')

ggplot(data = totalprops_pivot, aes(x = Category, y = Total)) +
  geom_bar(stat = "identity", fill = "lightblue4")+
  labs( 
    title = "Total Properties Receiving Flooding Adaptation Funding from 1985 - 2020", 
    x = "Adaptation Type", 
    y = "Number of Properties")
```

```{r}
totals_inflation_pivot <- pivot_longer(totals_inflation, `Ex-Situ`:`All Adaptation - Inflation`, names_to = "Category", values_to = "Total")

write.csv(totals_inflation_pivot, './Data/totalamountpaidinflation_explorationgraph')

ggplot(data = totals_inflation_pivot, aes(x = Category, y = Total)) +
  geom_bar(stat = "identity", fill = "lightblue3")+
  labs( 
    title = "Total Amount Paid for Flooding Adaptation from 1985 - 2020", 
    subtitle = "Amount Paid With and Without Inflation Adjustments to 2020 USD",
    x = "Adaptation Type", 
    y = "Amount Paid (USD)")
```

```{r}
ggplot(data = Databyyear, aes(x = programFy, y = Floodpropertiesperyear)) +
  geom_bar(stat = "identity", fill = "lightblue4")+
  labs( 
    title = "Number of Properties that Received Flood Adaptation Grants from 1985 - 2020", 
    x = "Year", 
    y = "Number of Properties")
```
```{r}
ggplot(data = inflationadjusted, aes(x = programFy, y = InflationAdjusted_AllAmountpaid)) +
  geom_bar(stat = "identity", fill = "lightblue3")+
  labs( 
    title = "Total Amount Paid for Flood Adaptation Grants 1985 - 2020", 
    x = "Year", 
    y = "Total Amount Paid (2020 USD)")
```
